name: myFirstWorkflow
# to get a trigger on every push in the repo in my branch
on: [push, workflow_dispatch]

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Running single command in job1
        run: echo "Hi, this my first Github workflow"
      - name: Checking OS release for Github Hosted Runner
        run: cat /etc/os-release
      - name: Calling Sleep
        run: sleep 20
 
  job2:
    name: Job2
    runs-on: ubuntu-latest
    steps:
      - name: Checking the hostname for Runner
        run: hostname
      - name: Running multiple commands
        run: 
          echo "Hi from M Khan."
          echo "Current time is `date`"
          sleep 20
        
        
